apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-app
  labels:
    app: swiggy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy-app
  template:
    metadata:
      labels:
        app: swiggy-app
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: swiggy-app
        image: 483216680875.dkr.ecr.us-east-1.amazonaws.com/test2:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
